/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/audioPlayer.vue')['default']
    Avatar: typeof import('./src/components/avatar.vue')['default']
    Calendar: typeof import('./src/components/calendar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Errorword: typeof import('./src/components/errorword.vue')['default']
    FontIcon: typeof import('./src/components/fontIcon.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    IframeView: typeof import('./src/components/iframeView.vue')['default']
    Keyword: typeof import('./src/components/keyword.vue')['default']
    KeywordItem: typeof import('./src/components/keywordItem.vue')['default']
    LessonItem: typeof import('./src/components/lessonItem.vue')['default']
    LineChart: typeof import('./src/components/chart/lineChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./src/components/share.vue')['default']
    Timeline3d: typeof import('./src/components/timeline3d.vue')['default']
    VideoPlayer: typeof import('./src/components/videoPlayer.vue')['default']
    WordChart: typeof import('./src/components/chart/wordChart.vue')['default']
  }
}
